/** Hex only — Clerk cannot reliably resolve CSS `var()` and treats transparent as dark. */
export const clerkAppearance = {
  layout: {
    logoPlacement: "none",
    socialButtonsVariant: "blockButton",
    unsafe_disableDevelopmentModeWarnings: true,
  },
  variables: {
    colorPrimary: "#1c3d32",
    colorBackground: "#fdfcf7",
    colorInputBackground: "#ffffff",
    colorInputText: "#261e0e",
    colorText: "#261e0e",
    colorTextSecondary: "#4e4735",
    colorTextOnPrimaryBackground: "#f8f5ea",
    colorNeutral: "#261e0e",
    colorDanger: "#9b2c2c",
    borderRadius: "8px",
    fontFamily: '"Source Sans 3", "Segoe UI", system-ui, sans-serif',
    fontSize: "16px",
  },
  elements: {
    rootBox: { width: "100%", colorScheme: "light" },
    cardBox: { width: "100%", boxShadow: "none" },
    card: {
      boxShadow: "none",
      backgroundColor: "#fdfcf7",
      border: "1px solid #d9d8cd",
      padding: "24px",
    },
    headerTitle: { display: "none" },
    headerSubtitle: { display: "none" },
    logoBox: { display: "none" },
    footerPages: { display: "none" },
    footerAction: { display: "none" },
    footer: { display: "none" },
    footerItem: { display: "none" },
    socialButtons: { display: "none" },
    formButtonPrimary: {
      backgroundColor: "#1c3d32",
      color: "#f8f5ea",
      boxShadow: "none",
      fontSize: "15px",
      fontWeight: "600",
      height: "44px",
      textTransform: "none",
    },
    formFieldInput: {
      height: "44px",
      fontSize: "16px",
      backgroundColor: "#ffffff",
      color: "#261e0e",
      borderColor: "#d9d8cd",
    },
    formFieldLabel: {
      color: "#261e0e",
      fontSize: "14px",
      fontWeight: "500",
    },
    formFieldHintText: { color: "#4e4735", fontSize: "13px" },
    dividerLine: { backgroundColor: "#d9d8cd" },
    dividerText: { color: "#4e4735" },
    identityPreviewText: { color: "#261e0e" },
    identityPreviewEditButton: { color: "#1c3d32" },
  },
}
