export const siteName = "Madalyn Robinson Foundation"
export const siteShortName = "Maddy's Foundation"
/** ~50–60 chars for SERP / social title space. */
export const siteTitle =
  "Madalyn Robinson Foundation — Events, Scholarships & Hope"
/** Keep ≤ ~125 characters for social truncations (playbook 05). */
export const siteDescription =
  "Spreading joy and light in honor of Madalyn Robinson — events, community, and hope."
export const ogImageAlt =
  "Madalyn Robinson Foundation — joy that still moves mountains"

function resolveSiteUrl(): string {
  const fromEnv = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "").trim()
  // Custom domain is pending DNS — don't emit OG URLs that 404 there.
  if (
    fromEnv &&
    !/^https?:\/\/(www\.)?maddysfoundation\.org$/i.test(fromEnv)
  ) {
    return fromEnv
  }
  if (process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL.replace(/\/$/, "")}`
  }
  return "https://maddys-foundation.vercel.app"
}

export const siteUrl = resolveSiteUrl()

/** Absolute OG / Twitter image paths (generated by app/opengraph-image.tsx). */
export const ogImagePath = "/opengraph-image"
export const twitterImagePath = "/twitter-image"

/** Venmo profile — override with NEXT_PUBLIC_DONATE_URL if needed. */
export const donateUrl =
  process.env.NEXT_PUBLIC_DONATE_URL?.trim() ||
  "https://venmo.com/u/MadalynRobinsonFoundation"
export const contactEmail =
  process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim() || ""
